name: Python Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - 'sdk/python/**'
  pull_request_target:
    branches: [ "main" ]
    paths:
      - 'sdk/python/**'
  workflow_dispatch:
  schedule:
    - cron: '0 0 1-31/15 * *'

env:
  OPENAI_API_TOKEN: ${{ secrets.OPENAI_API_TOKEN }}
  COHERE_API_TOKEN: ${{ secrets.COHERE_API_TOKEN }}
  ANTHROPIC_API_TOKEN: ${{ secrets.ANTHROPIC_API_TOKEN }}
  MISTRAL_API_TOKEN: ${{ secrets.MISTRAL_API_TOKEN }}
  PINECONE_API_TOKEN: ${{ secrets.PINECONE_API_TOKEN }}
  GROQ_API_TOKEN: ${{ secrets.GROQ_API_TOKEN }}
  QDRANT_URL: ${{ secrets.QDRANT_URL }}
  QDRANT_API_TOKEN: ${{ secrets.QDRANT_API_TOKEN }}
  MILVUS_URL: ${{ secrets.MILVUS_URL }}
  MILVUS_API_TOKEN: ${{ secrets.MILVUS_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Set up GCP Credentials
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Install dependencies
      working-directory: sdk/python
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r tests/requirements.txt

    - name: PyTest
      working-directory: sdk/python
      run: |
        pytest
